# Generated by Django 4.0.3 on 2022-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
    ]
