# Generated by Django 4.0.3 on 2022-03-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.TextField(default='https://storage.googleapis.com/kaggle-avatars/images/7541547-gr.jpg'),
        ),
    ]
