# Generated by Django 4.0.3 on 2022-04-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_design_screens_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hello',
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.TextField(default='https://jazsleyportfolio.s3.ap-southeast-1.amazonaws.com/resume.pdf'),
        ),
    ]
