# Generated by Django 4.0.3 on 2022-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_user_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('key_contribtion', models.TextField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('google_app_link', models.TextField()),
                ('apple_app_link', models.TextField()),
                ('picture_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.TextField(),
        ),
    ]
