# Generated by Django 4.0.3 on 2022-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_project_delete_post_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=30)),
            ],
        ),
    ]
